default: &default
  adapter: postgresql
  encoding: unicode
  database: dbproyecto
  pool: 5
  username: postgres
  password: 12345
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default

